// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package relay

type Node interface {
	IsNode()
}

type Faction struct {
	ID    string          `json:"id"`
	Name  *string         `json:"name"`
	Ships *ShipConnection `json:"ships"`
}

func (Faction) IsNode() {}

type IntroduceShipInput struct {
	FactionID        string `json:"factionId"`
	ShipNamed        string `json:"shipNamed"`
	ClientMutationID string `json:"clientMutationId"`
}

type IntroduceShipPayload struct {
	Faction          *Faction `json:"faction"`
	Ship             *Ship    `json:"ship"`
	ClientMutationID string   `json:"clientMutationId"`
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor"`
	EndCursor       *string `json:"endCursor"`
}

type Ship struct {
	ID   string  `json:"id"`
	Name *string `json:"name"`
}

func (Ship) IsNode() {}

type ShipConnection struct {
	Total    int         `json:"total"`
	Edges    []*ShipEdge `json:"edges"`
	PageInfo *PageInfo   `json:"pageInfo"`
}

type ShipEdge struct {
	Cursor string `json:"cursor"`
	Node   *Ship  `json:"node"`
}
